---
title: "Project 2 Climate Change"
subtitle: "Climate change and temperature anomalies"
image: pic03.jpg
output:
  html_document:
    theme: flatly
    highlight: zenburn
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>To study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>For each month and year, the dataframe shows the deviation of temperature from the normal (expected).</p>
<p>Select the year and the twelve month variables from the <code>weather</code> dataset. Convert the dataframe from wide to ‘long’ format.Name the new dataframe as <code>tidyweather</code>, name the variable containing the name of the month as <code>month</code>, and the temperature deviation values as <code>delta</code>.</p>
<pre class="r"><code>tidyweather &lt;- weather %&gt;% 
               select(Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec) %&gt;% 
               pivot_longer(c(Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec),
                            names_to = &quot;Month&quot;,
                            values_to = &quot;delta&quot;)

tidyweather</code></pre>
<pre><code>## # A tibble: 1,704 × 3
##     Year Month delta
##    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1  1880 Jan   -0.35
##  2  1880 Feb   -0.51
##  3  1880 Mar   -0.23
##  4  1880 Apr   -0.3 
##  5  1880 May   -0.06
##  6  1880 Jun   -0.16
##  7  1880 Jul   -0.18
##  8  1880 Aug   -0.26
##  9  1880 Sep   -0.23
## 10  1880 Oct   -0.32
## # … with 1,694 more rows</code></pre>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trend line. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<pre class="r"><code>tidyweather&lt;- tidyweather %&gt;%
              mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
              month = month(date, label=TRUE),
              year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (title = &quot;Weather Anomalies&quot;,
        x = &quot;Date&quot;,
        y = &quot;Delta&quot;) +
  NULL</code></pre>
<p><img src="/projects/project2/climate_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The graph shows clearly that as time has gone on, the number of weather anomalies has gone up drastically. This corroborates the claim that scientists have made on humans bringing about climate change and the effect of increased greenhouse gas emissions on our environment.</p>
<p>Is the effect of increasing temperature more pronounced in some months? Use <code>facet_wrap()</code> to produce a separate scatter plot for each month, again with a smoothing line.</p>
<p><img src="/projects/project2/climate_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The graphs show a roughly similar trend in weather anomalies in each individual month. The effects of increasing temperature are slightly more pronounced in November and December. This may be because these months come at the heart of winter and therefore show a bit greater variation and more extreme values in the northern hemisphere.</p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calculates a temperature anomaly, as difference form the base period of 1951-1980. The code below creates a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We remove data before 1800 and before using <code>filter</code>. Then, we use the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to. We can assign the different periods using <code>case_when()</code>.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
              filter(Year&gt;= 1881) %&gt;%     
              mutate(interval = case_when(
                    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
                    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
                    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
                    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
                    TRUE ~ &quot;2011-present&quot;))</code></pre>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in. Set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval)) +
  geom_density(alpha=0.2) +   
  theme_bw() +                
  labs (title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
        x = &quot;Delta&quot;,
        y = &quot;Density&quot;)</code></pre>
<p><img src="/projects/project2/climate_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The density plot shows the trend of how the delta (monthly deviations) has progressively increased as time has gone on. This is what we expect as, in line with modern conceptions of climate change, the number of monthly temperature anomalies has gone up as humankind’s industrial output has increased. Between 1881-1920, we can see a negative delta. This could be explained by the massive volcanic eruption of Krakatoa in 1883 whose ash clouds were so significant that they blocked and reflected more than usual the Sun’s rays, thus reducing global temperatures.</p>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  summarise(na.rm=TRUE,annual_average_delta=mean(delta)) 

ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  geom_smooth() +
  theme_bw() +
  labs (title = &quot;Average Yearly Anomaly&quot;, 
        x = &quot;Year&quot;,
        y = &quot;Average Annual Delta&quot;)</code></pre>
<p><img src="/projects/project2/climate_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>From the last graph, we saw how each period’s delta was either 0 or close to 0, until after the 1950s when human fossil fuel emissions increased. Here, we can observe across the whole period how the number of anomalies has consistently grown, especially since 1960. This is also consistent with our notion of global warming.</p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Then we construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package. Recall that the dataframe <code>comparison</code> has already grouped temperature anomalies according to time intervals; we are only interested in what is happening between 2011-present.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
              filter(interval %in% &quot;2011-present&quot;) %&gt;% 
              summarise(mean_delta = mean(delta),
              sd_delta = sd(delta),
              count = n(),
              t_critical = qt(0.975,count-1),
              se_delta = sd(delta)/sqrt(count),
              margin_of_error = t_critical * se_delta,
              delta_low = mean_delta - margin_of_error,
              delta_high = mean_delta + margin_of_error)

formula_ci</code></pre>
<pre><code>## # A tibble: 1 × 8
##   mean_delta sd_delta count t_critical se_delta margin_of_error delta_low
##        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt;     &lt;dbl&gt;
## 1         NA       NA   132       1.98       NA              NA        NA
## # … with 1 more variable: delta_high &lt;dbl&gt;</code></pre>
<pre class="r"><code>library(infer)
set.seed(1234)
boot_delta &lt;- comparison %&gt;%
              filter(interval %in% &quot;2011-present&quot;) %&gt;%
              specify(response = delta) %&gt;%
              generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
              calculate(stat = &quot;mean&quot;)

bootstrapping_CI &lt;- boot_delta %&gt;% 
                    get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)

bootstrapping_CI</code></pre>
<pre><code>## # A tibble: 1 × 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.01     1.11</code></pre>
</div>
<div id="implication" class="section level2">
<h2>Implication</h2>
<p>By constructing a confidence interval using one sample, the data show us that there is a 95% chance that the true average annual data mean is contained in the confidence interval (CI) between 1.01 and 1.11. The CI previously mentioned was constructed using one sample (the data) for the northern hemisphere, allowing us to infer about temperature anomalies in that zone of the earth, but not for the entire planet. It is not possible to know with certainty where the true parameter of a mean lies with only one sample (in this case, data for the northern hemisphere). To address the sampling variability problem, bootstrapping may be useful. Repeatedly sampling with replacement via Bootstrapping (BTS) creates resamples (in this case 1,000) and finally calculates 1,000 mean statistics to calculate a new confidence interval. Using the BTS method, there is a 95% chance that the true average annual delta mean is between 1.02 and 1.11. An additional benefit of using BTS is that the data distribution will approach a normal one because of the Central Limit Theorem.</p>
</div>
